# Zenbook Duo FN bridge mapping file
#
# Format:
#   ABS_MISC_VALUE=KEY_NAME
#
# Notes:
# - Lines starting with # are comments.
# - Empty lines are ignored.
# - KEY_NAME must be a valid Linux input key symbol from evdev, e.g.:
#   KEY_BRIGHTNESSUP, KEY_BRIGHTNESSDOWN, KEY_MICMUTE
#
# Defaults observed on UX8406 keyboard BT interface (event262 on test setup):

# FN + ESC KEY -> 78 // Unable to make it work atm
78=KEY_FN_ESC

#VOL_MUTE [F1] -> Works as a normal key event
#VOL_DOWN [F2] -> Works as a normal key event
#VOL_UP [F3] -> Works as a normal key event

#KBD ILLUMINATION TOGGLE [F4] -> 199 // Unable to make it work atm, but it sends a key event with code 199, which corresponds to KEY_KBDILLUMTOGGLE in Linux input subsystem. This key is typically used to toggle the keyboard backlight on and off.
199=KEY_KBDILLUMTOGGLE 

# BRIGHTNESSDOWN [F5] -> 16
16=KEY_BRIGHTNESSDOWN 

# BRIGHTNESSUP [F6] -> 32
32=KEY_BRIGHTNESSUP

# SWITCH VIDEO MODE [F7] -> Works as a normal key event

# SWITCH SCREENS CONTENT TOGGLE [F8] -> 156
156=KEY_SWITCHVIDEOMODE 

# MIC MUTE KEY [F9] -> 124
124=KEY_MICMUTE 

# Bluetooth TOGGLE [F10] -> Doesn't send any key event.

# EMOJI PICKER [F11] -> 126
126=KEY_EMOJI_PICKER 


# MY ASUS KEY [F12] -> 134
134=KEY_MICMUTE

# SECOND DISPLAY TOGGLE (next to MyAsus Key) -> 106
106=KEY_DISPLAYTOGGLE 

